import 'package:flutter/material.dart';

const MaterialColor materialColor = Colors.blue;
const primaryColor = Colors.blue;
const secondaryColor = Color(0xFF21305A);
const bgColor = Color(0xffF1F7FF);
const deepBgColor = Color(0xffEFF4FF);
const bgColorDark = Color(0xffB6D5FF);
const searchBarBgColor = Color(0xffFAFAFA);
const buttonColor = Color(0xffB81E25);
const cardColor = Color(0xffFFFFFF);
const textColor = Color(0xff585D69);
const textLight = Color(0xFF9D9D9D);
const irisOrange = Color(0xFFF37042);
const irisYellow = Color(0xFFFDB94A);
const mbOnlineColor = Color(0xFF3D00BD);
const fuschiaText = Color(0xFF1D1D1F);
const fuschiaBlueGem = Color(0xFF494099);
const defaultPadding = 16.0;
const irisStudio = Color(0xFF6E52A2);
const fuschiaRed = Color(0xFFB80F0A);
